project-violet/violet

lib/pages/splash/splash_page.dart
pubspec.lock
pubspec.yaml

(splash) Use Radio widgets for database tiles

---

assets/locale/en.json
assets/locale/eo.json
assets/locale/ko.json
assets/locale/zh.json
assets/locale/zh_Hans.json
assets/locale/zh_Hant.json
lib/pages/main/info/info_page.dart
lib/pages/settings/settings_page.dart

(translation) Change Github to GitHub

---

lib/pages/search/search_bar_page.dart

(search) Fix switches to respond on tap

---

lib/pages/settings/settings_page.dart

(settings-page) Fix switches to respond on tap

---

pubspec.yaml

2.10 is the highest version without null safety.

(dart) Update Dart to version 2.10

---

lib/widgets/article_item/article_list_item_widget.dart

This patch is using [collection if](https://dart.dev/guides/language/language-tour#collection-operators) feature so #46 should be merged before.

(article-item) Move date position in _DetailWidget

---

lib/settings/settings.dart

(settings) Fix app startup hang issue

---

lib/pages/after_loading/afterloading_page.dart
lib/pages/settings/settings_page.dart

This patch is kind of *hacky*. Later provider or something can be used instead.
This will improve the UX which was confusing.

(settings) Apply 'use drawer' option changes instantly

---

lib/pages/search/search_page.dart

Code for diagnosis is included too.
'try-finally' ensures that the semaphore will be released even if an exception occurs.

(search) Mitigate search query semaphore problem

---

pubspec.yaml

Copy-and-pasted from the README.md file.

(dart) Update pubspec description

---

lib/pages/community/user_status_card.dart

(community) Refine user status card to fix rendering issues

---

lib/other/named_color.dart
lib/pages/after_loading/afterloading_page.dart
lib/pages/splash/splash_page.dart

(other) Introduce NamedColor extension to replace _colorToString

---

lib/pages/after_loading/afterloading_page.dart
lib/version/update_sync.dart

There were 4 `Scaffold` generation code.
Diff is so large, so please use split view for review.

(afterloading) Reduce code duplication

---

lib/pages/article_info/article_info_page.dart
lib/pages/bookmark/group/group_article_list_page.dart
lib/pages/bookmark/group/group_artist_list.dart
lib/pages/bookmark/group_modify.dart
lib/pages/main/main_page2.dart
lib/pages/search/search_bar_page.dart
lib/pages/settings/settings_page.dart
lib/pages/settings/tag_selector.dart
lib/pages/splash/splash_page.dart

(trivial) Migrate RaisedButton to ElevatedButton

---

lib/main.dart
lib/pages/after_loading/afterloading_page.dart

(afterloading) Organize code

---

lib/component/hitomi/hitomi.dart
lib/other/dialogs.dart
lib/pages/article_info/article_info_page.dart
lib/pages/bookmark/bookmark_page.dart
lib/pages/bookmark/group/group_article_list_page.dart
lib/pages/bookmark/group/group_artist_list.dart
lib/pages/bookmark/group_modify.dart
lib/pages/community/community_page.dart
lib/pages/community/signin_dialog.dart
lib/pages/community/signup_dialog.dart
lib/pages/community/user_status_card.dart
lib/pages/database_download/database_download_page.dart
lib/pages/download/download_page.dart
lib/pages/main/card/views_card.dart
lib/pages/main/main_page.dart
lib/pages/main/main_page2.dart
lib/pages/main/patchnote/patchnote_page.dart
lib/pages/settings/log_page.dart
lib/pages/settings/settings_page.dart
lib/pages/splash/splash_page.dart
lib/pages/viewer/viewer_page.dart
lib/widgets/article_item/article_list_item_widget.dart

(trivial) Organize dialog functions

---

lib/algorithm/distance.dart
lib/main.dart
lib/pages/main/artist_collection/artist_collection_page.dart
lib/pages/main/artist_collection/artist_list_page.dart

At first I just wanted to hide "(null)" but eventually...!

(artist-collection) Hide null number and organize code

---

lib/pages/search/search_page.dart

I want to use loggers or something instead of `print` function. But not now.

(search) Mitigate and investigate search failure problem

---

lib/downloader/native_downloader.dart
lib/main.dart
lib/other/dialogs.dart
lib/pages/article_info/article_info_page.dart
lib/pages/artist_info/article_list_page.dart
lib/pages/community/signup_dialog.dart
lib/pages/main/main_page.dart
lib/pages/main/main_page2.dart
lib/pages/search/search_bar_page.dart
lib/pages/search/search_page.dart
lib/pages/settings/settings_page.dart
lib/pages/splash/splash_page.dart
lib/pages/viewer/viewer_page.dart

This patch resolves all issues except:
> info: This class (or a class that this class inherits from) is marked as '@ immutable', but one or more of its instance fields aren't final: ...
The above pattern needs redesigning the classes.

(trivial) Clean up Dart analysis issues

---

lib/pages/search/search_page.dart

(search) Refine error toast rendering

---

lib/pages/article_info/article_info_page.dart
lib/pages/bookmark/group_modify.dart
lib/pages/community/signin_dialog.dart
lib/pages/community/signup_dialog.dart

(trivial) Fix easy cases of immutable annotation warning

---

.github/workflows/build.yml

After merging, you need to modify the action by referring to the comments.

(chore) Add ios build action

---

.github/workflows/build.yml

need edit workflow file because `lib/server/salt.dart` `lib/server/wsalt.dart` `getVaild` after merge

chore(github-actions): add android build

---

lib/component/hitomi/hitomi.dart

This PR solves the problem that some works are not visible

fix(hitomi): fix image URL rule

---

.vscode/launch.json
android/app/build.gradle
android/app/src/debug/AndroidManifest.xml
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/xyz/project/violet/MainActivity.kt
android/app/src/main/res/values-night/styles.xml
android/app/src/main/res/values/styles.xml
android/app/src/profile/AndroidManifest.xml
android/build.gradle
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties
android/settings.gradle
android/settings_aar.gradle
ios/Flutter/AppFrameworkInfo.plist
ios/Flutter/Debug.xcconfig
ios/Flutter/Release.xcconfig
ios/Podfile
ios/Runner/Info.plist
web/index.html
windows/CMakeLists.txt
windows/flutter/CMakeLists.txt
windows/runner/CMakeLists.txt
windows/runner/utils.cpp

패키지 업데이트 제외
1. Android
- Gradle 업데이트
- 불필요 세팅 삭제
- Android Manifest url_launcher 설정 추가
- MainActivaty 수정
2. IOS
- 최소 버전 변경 
- xcconfig 수정
- Podfile permission_handler 세팅 추가
- Info.plist url_launcher 설정 추가
- Migrate Flutter 3.0
3. Web
- Migrate Flutter 3.0
4. Windows
- Migrate Flutter 3.0

Migrate Flutter 3.0 Build Setting

---

lib/component/eh/eh_headers.dart
lib/component/eh/eh_provider.dart
lib/downloader/isolate_downloader.dart
lib/main.dart
lib/pages/article_info/article_info_page.dart
lib/pages/bookmark/group/group_article_list_page.dart
lib/pages/community/community_page.dart
lib/pages/community/user_status_card.dart
lib/pages/community/user_status_card_dead.dart
lib/pages/database_download/database_download_page.dart
lib/pages/download/download_page.dart
lib/pages/lock/lock_screen.dart
lib/pages/main/info/lab_page.dart
lib/pages/main/main_page.dart
lib/pages/settings/lock_setting_page.dart
lib/pages/settings/route.dart
lib/pages/settings/settings_page.dart
lib/pages/splash/splash_page.dart
lib/server/community/anon.dart
lib/server/violet.dart
lib/settings/settings.dart
lib/version/sync.dart
pubspec.lock
pubspec.yaml

1. Update shared_preferences
2. Cleanup SharedPreferences.getInstance()

Cleanup `shared_preferences`

---

lib/checker/checker.dart
lib/component/hitomi/hitomi.dart
lib/database/user/bookmark.dart
lib/database/user/download.dart
lib/database/user/search.dart
lib/other/dialogs.dart
lib/pages/article_info/article_info_page.dart
lib/pages/artist_info/artist_info_page.dart
lib/pages/community/community_page.dart
lib/pages/community/user_status_card_dead.dart
lib/pages/database_download/database_download_page.dart
lib/pages/database_download/decompress.dart
lib/pages/download/download_page.dart
lib/pages/main/info/lab/bookmark/bookmarks.dart
lib/pages/search/search_bar_page.dart
lib/pages/settings/settings_page.dart
lib/pages/settings/tag_rebuild_page.dart
lib/pages/viewer/others/scrollable_positioned_list/src/positioned_list.dart
lib/pages/viewer/others/scrollable_positioned_list/src/scrollable_positioned_list.dart
lib/pages/viewer/others/scrollable_positioned_list/src/viewport.dart
lib/pages/viewer/others/scrollable_positioned_list/src/wrapping.dart

This PR fixes relatively easy issues to fix.
Remaining issues are related to "proper null-safety implementation" so it takes time to fix them.
Part 2, otanoshimini.

chore: fix Dart Analysis issues - operand can't be null (part 1)

---

lib/pages/database_download/decompress.dart

The ARM based Android emulator is being used in Apple silicon Macs. In order to support new Macs, lib7zr.so selection should not be fixed to x86 even if `kDebug`.

downloader: simplify lib7zr.so resolving to support Apple silicon Mac dev env

---

lib/pages/after_loading/afterloading_page.dart

- Use animated scroll? or not?
- Currently using animateTo() method and its duration is 200ms. is it properly configured?

feat: animate scroll to top when tap BottomNavigationBar icon

---

lib/pages/viewer/vertical_webview_viewer_page.dart
pubspec.yaml

WebView - fix script resolution

---

lib/pages/community/community_page.dart
lib/pages/community/user_status_card.dart
lib/pages/community/user_status_card_dead.dart
lib/pages/main/main_page.dart

cf. https://api.flutter.dev/flutter/material/Badge-class.html

chore: fix to use named import for badges to support Flutter 3.7

---

lib/database/database.dart

db: fix database manager for proper initial database downloading

---

lib/component/eh/eh_bookmark.dart
lib/component/hentai.dart
lib/component/hentai_download_manager.dart
lib/component/hitomi/hitomi.dart
lib/component/hitomi/hitomi_parser.dart
lib/database/user/bookmark.dart
lib/pages/bookmark/group/group_article_list_page.dart
lib/pages/settings/login/ehentai_login.dart
lib/pages/settings/settings_page.dart

- project-violet/violet/issues/271
> - [Fix parsing artist](https://github.com/project-violet/violet/pull/277/commits/b95cd05df951706ecf3e731084289a8602a1041e)
- project-violet/violet/issues/269
> - [Add _tryGetArticleFromEhentai](https://github.com/project-violet/violet/pull/277/commits/7a65e67924bb2fa39c4c7b3a900adac432a4d4b0)
> - [Fix null-check](https://github.com/project-violet/violet/pull/277/commits/92374bfdffe9ea54e1cdea03bfc630f220481283)
> - [Add E-hentai to idSearch](https://github.com/project-violet/violet/pull/277/commits/47227a4448c2960c0438093307303e5c87c812c0)
> - [Use for-in instead of forEach](https://github.com/project-violet/violet/pull/277/commits/db6b9cb6b6a8870ba576a364b898cb16bab0de3f)
- project-violet/violet/issues/273
> - [Use ExistOnHitomi=1 only …

Dev without linux build

---

pubspec.yaml

Reverts project-violet/violet#284

Revert "Remove unused package"

---

android/app/src/main/AndroidManifest.xml
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Info.plist

closes https://github.com/project-violet/violet/issues/149

Support deeplink violet://*

---

lib/settings/device_type.dart

Change deprecated singleton member

---

lib/pages/bookmark/group/group_article_list_page.dart

- https://github.com/project-violet/violet/issues/301

Fix handle article from web in group_article_list_page

---

android/app/src/main/AndroidManifest.xml

- https://github.com/project-violet/violet/issues/302
- https://stackoverflow.com/questions/30605249/android-create-a-schema-for-my-app-that-will-open-from-a-webpage-link

Fix app icon dissapear on android

---

lib/component/hentai.dart

- https://github.com/project-violet/violet/issues/311
> - https://github.com/project-violet/violet/pull/310#discussion_r1439095047
> - https://github.com/project-violet/violet/pull/310#discussion_r1439095074

Fix idSearch

---

lib/pages/splash/splash_page.dart
lib/settings/settings.dart

- Fix chinese default settings
- Fix no applying splash language settings

Fix initial include tags

---

lib/pages/settings/settings_page.dart

Refactor Settings Page

---

lib/pages/settings/tag_rebuild_page.dart

Refactor tag rebuild indexing

---

lib/database/database.dart
lib/database/user/bookmark.dart
lib/database/user/record.dart
lib/database/user/user.dart
lib/pages/splash/splash_page.dart

https://github.com/project-violet/violet/blob/4c302037b2105ac9cebb92f4681aef9da6308860/lib/widgets/article_item/article_list_item_widget_controller.dart#L90-L102

Fix too many database query

---

lib/database/user/record.dart

fix recording error cuz by https://github.com/project-violet/violet/pull/318

DB-Record: Remove datetime comparing

---

lib/component/hentai.dart

- https://github.com/project-violet/violet/issues/327

Fix typo in url

---

lib/component/hentai.dart
lib/model/article_list_item.dart
lib/widgets/article_item/article_list_item_widget.dart

- https://github.com/project-violet/violet/issues/325
- https://github.com/project-violet/violet/issues/322

Fix _ArticleListItemWidgetState

---

assets/locale/en.json
assets/locale/eo.json
assets/locale/it.json
assets/locale/ja.json
assets/locale/ko.json
assets/locale/pt.json
assets/locale/zh.json
assets/locale/zh_Hans.json
assets/locale/zh_Hant.json
lib/component/eh/eh_parser.dart
lib/component/git/git_bookmark.dart
lib/component/hentai.dart
lib/model/article_info.dart
lib/pages/search/search_page_controller.dart
lib/pages/settings/settings_page.dart
lib/settings/settings.dart
test/test_component.dart

- https://github.com/project-violet/violet/issues/348
> - [Fix git import db](https://github.com/project-violet/violet/pull/347/commits/bc5aeb6d38d285ac2f8e84043f8113accb94a65e)
- https://github.com/project-violet/violet/issues/349
> - [Add expunged hash](https://github.com/project-violet/violet/pull/347/commits/12c0bea50a65b3754be162937e68cdf9a2c48bc1)
> - [Fix error handle in find hash](https://github.com/project-violet/violet/pull/347/commits/3872e77c2e7b9ea952297957f30cdc1b41622a18)
- https://github.com/project-violet/violet/issues/340
> - [Add Settings.searchExpunged](https://github.com/project-violet/violet/pull/347/commits/8ba5523e217a4b2fae365b504daf9ecd2b0320b7)
- https://github.com/project-violet/violet/issues/350
> - [Add …

Fix something

---

test/component_test.dart

Enable EHentai Gallery Parse

---

lib/pages/settings/settings_page.dart

fix https://github.com/project-violet/violet/issues/360

Fix settings page ui bugs

---

lib/database/user/bookmark.dart
lib/pages/main/info/lab/crop_bookmark.dart
lib/pages/main/info/lab_page.dart
lib/pages/viewer/image/file_image.dart
lib/pages/viewer/image/provider_image.dart
lib/pages/viewer/vertical_viewer_page.dart
pubspec.lock
pubspec.yaml

close https://github.com/project-violet/violet/issues/361

Crop Bookmark

---

lib/database/user/bookmark.dart
lib/pages/article_info/article_info_page.dart
lib/pages/main/info/lab/crop_bookmark.dart
lib/pages/viewer/image/file_image.dart
lib/pages/viewer/image/provider_image.dart
lib/pages/viewer/viewer_page.dart
lib/pages/viewer/widget/double_point_listener.dart

close https://github.com/project-violet/violet/issues/365
close https://github.com/project-violet/violet/issues/366

Advance Crop 2

---

lib/pages/main/info/lab/crop_bookmark.dart

Reverts project-violet/violet#369

Revert "Remove progress circular bar"

---

.github/workflows/build.yml
ios/Runner/Info.plist
lib/pages/main/info/lab/crop_bookmark.dart
lib/widgets/cupertino_switch_list_tile.dart
pubspec.lock
pubspec.yaml

Advance Crop Bookmark 4

---

lib/pages/artist_info/article_list_page.dart
lib/pages/artist_info/artist_info_page.dart
lib/pages/bookmark/group/group_article_list_page.dart
lib/pages/bookmark/group/group_artist_article_list.dart
lib/pages/bookmark/group/group_artist_list.dart
lib/pages/bookmark/record_view_page.dart
lib/pages/search/search_page.dart
lib/pages/segment/three_article_panel.dart
lib/pages/viewer/horizontal_viewer_page.dart
lib/pages/viewer/overlay/viewer_overlay.dart
lib/pages/viewer/viewer_controller.dart
lib/pages/viewer/viewer_page.dart
lib/settings/settings.dart
lib/widgets/article_item/article_list_item_widget.dart
lib/widgets/article_item/article_list_item_widget_controller.dart
pubspec.lock
pubspec.yaml

Advance Tablet UI

---

rust_builder/cargokit/build_tool/lib/src/android_environment.dart
rust_builder/cargokit/build_tool/lib/src/builder.dart
rust_builder/cargokit/run_build_tool.sh

https://github.com/project-violet/violet/issues/419

Fix cargokit

---

.github/workflows/violet-build.yml
violet/lib/component/hitomi/displayed_tag.dart
violet/lib/component/hitomi/hitomi.dart
violet/lib/component/hitomi/tag_translate.dart
violet/lib/pages/download/download_routine.dart
violet/lib/pages/search/search_bar_page.dart
violet/lib/pages/settings/tag_selector.dart
violet/test/component_test.dart
violet/test/query_test.dart
violet/test/translate_test.dart

Refactor 003

---

violet/lib/pages/settings/login/ehentai_login.dart

Try jsonDecode in try/catch

---

violet/assets/locale/en.json
violet/assets/locale/eo.json
violet/assets/locale/it.json
violet/assets/locale/ja.json
violet/assets/locale/ko.json
violet/assets/locale/pt.json
violet/assets/locale/zh.json
violet/assets/locale/zh_Hans.json
violet/assets/locale/zh_Hant.json
violet/lib/component/hentai.dart
violet/lib/pages/settings/settings_page.dart
violet/lib/settings/settings.dart

Fix of #550

---

violet/lib/pages/settings/settings_page.dart

Fix f_cats scrollable

---

.github/workflows/violet-build.yml

Fix violet-build.yml

---

.github/workflows/violet-build.yml

Bump up setup-java to main

---

hsync/hsync/Syncronizer.cs
hsync/hsync/SyncronizerLowPerf.cs
violet/doc/dev.md
violet/lib/component/hentai.dart
violet/lib/component/hentai_download_manager.dart
violet/lib/component/hitomi/hitomi_provider.dart
violet/lib/network/wrapper.dart
violet/lib/pages/download/download_page.dart
violet/lib/pages/lab/lab/bookmark/bookmarks_article_list.dart
violet/lib/pages/settings/route.dart
violet/lib/script/script_manager.dart
violet/lib/script/script_webview.dart
violet/test/get_test.dart
violet/test/script_test.dart

Could not retrieve information from ltn.hitomi.la.
After investigating, I was able to confirm that the request was being sent to ltn.gold-usergeneratedcontent.net.

fix: change hostname to gold-usergeneratedcontent.net

---

violet/lib/thread/semaphore.dart

Fix infinite loading

---

violet/lib/component/eh/eh_bookmark.dart

Fix import bookmark from ehentai

---

violet/lib/database/user/bookmark.dart
violet/lib/pages/viewer/image/image_crop_bookmark.dart

Fix minor bugs of crop, artist bookmark
